spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: midas-core-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: '*'
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
      #show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect

general:
  kafka-topic: transactions-topic

  #logging:
   # level:
    #  org.springframework.kafka: DEBUG
     # com.jpmc.midascore: DEBUG

server:
  port: 33400
